-- La aplicación accede a estas tablas exclusivamente desde rutas de servidor
-- con SUPABASE_SECRET_KEY / SUPABASE_SERVICE_ROLE_KEY. Ningún cliente público
-- recibe acceso directo sin una política RLS explícita.
ALTER TABLE "clubs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sedes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "equipos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usuarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jugadores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "eventos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "asistencias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mensualidades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pagos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ingresos_club" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "formaciones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "goles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tarjetas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cambios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "evaluaciones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chat_miembros" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mensajes_chat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invitaciones_club" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_ClubAdmins" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "solicitudes_inscripcion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "background_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
